---
# tasks file for role_nginx_server---
- name: install common packages
  apt: 
    update_cache=yes
    state=latest
    name={{item}}
  with_items: 
  - curl
  - iputils-ping
  become: yes
#- name: filesystem resources
#  file:
#    path: /usr/src/ansible_workspace
#    state: directory
#    mode: '0755'
#  become: yes
- name: create multiples directories system resources in a loop
  file:
    path: "/usr/src/{{ item }}"
    owner: root
    group: root
    state: directory
    recurse: yes
    mode: '0755'
  #register: file_output
  #loop:
  #  - ansible_workspace
  #  - ansible_workspace/projectApp/checkout
  with_items: ["ansible_workspace", "ansible_workspace/projectApp", "ansible_workspace/projectApp/checkout"]
  become: yes


- name: check for success
  stat:
    path: "/usr/src/ansible_workspace/projectApp/checkout"
  register: result
  become: yes


- name: do something with file if exists
  command: echo "directories /usr/src/ansible_workspace/projectApp/checkout exist"
  when: result.stat.exists
 
 
